name = "rproteinfinder"

[install]
completion = true
quiet = false
optimize = 2
nthreads = 16

[sysimg]
incremental=false
filter_stdlibs=true

[sysimg.precompile]
execution_file = ["deps/precompile.jl"]